# Base configs
baseurl: "https://whilehak.github.io/photography/"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "whileraw"
subtitle: "my photos"
author: "Kyle Pak"
header:
 title: "whileraw"
 subtitle: "Kyle Pak"
footer:
 name: "hello there"
 bio: "I'm a photographer based in LA and SoCal. "
 github: ""
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/whileraw"
  github: "https://www.github.com/whilehak"
